---
deployment:
  tasks:
    - export APPDIR=/home/cnffvpvlg/knownmenick-next.js
    - export NODEENV=/home/cnffvpvlg/nodevenv/knownmenick-next.js/22/bin/activate
    - . "$NODEENV"
    - cd "$APPDIR"
    - /bin/npm ci --no-audit --no-fund
    - /bin/npm run build
    - mkdir -p tmp
    - touch tmp/restart.txt
